import google.generativeai as genai
import os
import json

class GenerateImageComponents:
    def __init__(self):
        genai.configure(api_key=os.environ.get("API_KEY"))
        self.model = genai.GenerativeModel(model_name="gemini-1.5-flash")
        self.PROMT = 'generate me a single sentence title and two sentence description for this image in JSON format'

    def upload_to_gemini(self, path, mime_type=None):
        file = genai.upload_file(path, mime_type=mime_type)
        return file
        

    def getCaptionAndDescription(self, image):
        image.save(os.path.join('',image.filename))
        img = self.upload_to_gemini(image.filename, mime_type="image/jpeg")
        os.remove(image.filename)
        part = [img, self.PROMT]
        response = self.model.generate_content(part)
        l = []
        print(response.text)
        try:
            file = open('req.txt', 'w')
            print(response.text)
            file.write(response.text)
            file.close()
            lines = []
            my_file = open("req.txt", "r")
            data = my_file.read() 
            my_file.close()
            data_into_list = data.split("\n")
            title = data_into_list[2].split('": ')[1].split('"')[1]
            description = data_into_list[3].split('": ')[1].split('"')[1]
            l.append(description)
            l.append(title)
        except IndexError as e:
            my_file = open("req.txt", "r")
            data = my_file.read()
            my_file.close()
            data_into_list = data.split("\n")
            title = data_into_list[4].split('": ')[1].split('"')[1]
            description = data_into_list[5].split('": ')[1].split('"')[1]
            l.append(description)
            l.append(title)
        except Exception as e:
            l.append("This error in generating a description is due to unable to parse the response generated by the AI model")
            l.append("Error generating caption due to unable to format the response")

        os.remove("req.txt")
        return l